# OpenJDK 17 및 Maven 설치
FROM eclipse-temurin:23-jdk

WORKDIR /app

# 프로젝트 복사
COPY . /app

# Gradle Wrapper 실행 권한 부여
RUN chmod +x ./gradlew

# Gradle 빌드 실행
RUN ./gradlew build -x test

# JAR 파일 위치 확인 후 실행 (Gradle 빌드 결과물 사용)
RUN ls -lah build/libs/

ENTRYPOINT ["java", "-jar", "build/libs/ssacle-0.0.1-SNAPSHOT.jar"]
